# ConstraintTemplate definition
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8smaxunavailable
spec:
  crd:
    spec:
      names:
        kind: K8sMaxUnavailable
      validation:
        # OpenAPI v3 schema to validate parameters
        openAPIV3Schema:
          properties: {}
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8smaxunavailable

        violation[{"msg": msg}] {
          input.review.kind.kind == "PodDisruptionBudget"
          provided := input.review.object.spec.maxUnavailable
          provided == 0
          msg := sprintf("PodDisruptionBudget maxUnavailable is %v, must not be 0", [provided])
        }
